version: "3.7"

services:
  app:
    build:
      context: ./app
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./app:/go/src/app
    env_file: .env
  db:
    build:
      context: ./db/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      TZ: "Asia/Tokyo"
    env_file: .env
    volumes:
      - ./db/mysql/migrations:/docker-entrypoint-initdb.d
      - ./db/mysql/log:/var/log/mysql
      - ./db/mysql/conf.d:/etc/mysql/conf.d
