name: go_integration_test
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master
      - develop

jobs:
  test:
    env:
      GOPATH: ${{ github.workspace }}
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.2
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ./src/github.com/${{ github.repository }}
      - name: run docker-compose
        run: |
          export DOCKER_BUILDKIT=1
          export COMPOSE_DOCKER_CLI_BUILD=1
          export AWS_S3_ACCESS_KEY_ID=${{ secrets.AWS_S3_ACCESS_KEY_ID}}
          export AWS_S3_SECRET_ACCESS_KEY=${{ secrets.AWS_S3_SECRET_ACCESS_KEY}}
          docker-compose build
          docker-compose up -d
        working-directory: ./src/github.com/${{ github.repository }}
      - name: sleep
        run: |
          sleep 10
        working-directory: ./src/github.com/${{ github.repository }}
      - name: Test
        run: make integration_tests
        working-directory: ./src/github.com/${{ github.repository }}/app
